---
- name: Get MetalLB Descriptor
  get_url:
    url: https://raw.githubusercontent.com/metallb/metallb/{{s_var_vmetallb}}/manifests/metallb.yaml
    dest: /home/{{s_var_user}}/app/cicd/challenges/KinD/deploy/xperiment/kind-k8s/gnu/config/metallb.yaml 
    owner: "{{ s_var_user }}"
    group: "{{ s_var_user }}"
    mode: 0755

- name:  MetalLB ConfigMap Descriptor Creation
  copy:
    remote_src: true
    dest: /home/{{s_var_user}}/app/cicd/challenges/KinD/deploy/xperiment/kind-k8s/gnu/config/kind-config.yaml
    content: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: metallb-system
        name: config
      data:
        config: |
          address-pools:
          - name: docker-nix-server
            protocol: layer2
            addresses:
            - #NET_DOCKER_CLASSC#.200-#NET_DOCKER_CLASSC#.250
    mode: 0755
    owner: "{{ s_var_user }}"
    group: "{{ s_var_user }}"
  when: inventory_hostname in groups['kind-pg-0']
