---
- name: Get KinD CLI binary
  get_url:
    url: https://github.com/kubernetes-sigs/kind/releases/download/{{s_var_kindcli}}/kind-linux-amd64
    dest: /home/{{s_var_user}}/kind-linux-amd64
    owner: "{{ s_var_user }}"
    group: "{{ s_var_user }}"
    mode: 0755

- name: Checking if the binary file exists
  stat: 
    path: /home/{{s_var_user}}/kind-linux-amd64
  register: kind_cli_origin_file_data

- name: Move content of decompressed archive to directory
  copy:
    remote_src: true
    src: /home/{{s_var_user}}/kind-linux-amd64
    dest: /home/{{s_var_user}}/util/kind/{{s_var_kindcli}}/bin/kind
    owner: "{{ s_var_user }}"
    group: "{{ s_var_user }}"
    mode: 0755
  when: kind_cli_origin_file_data.stat.exists

- name: Update binary permissions for pre-adjustment
  file:
    path: /home/{{s_var_user}}/util/kind/{{s_var_kindcli}}/bin/kind
    owner: "{{ s_var_user }}"
    group: "{{ s_var_user }}"
    mode: a-x

- name: Update binary permissions for alignment
  file:
    path: /home/{{s_var_user}}/util/kind/{{s_var_kindcli}}/bin/kind
    owner: "{{ s_var_user }}"
    group: "{{ s_var_user }}"
    mode: 0755
    #mode: u=rwX,g=rX,o=rX
    #recurse: yes

- name: Add binary to PATH and .bash profile
  command: |
    sh -c 'cat << EOF >> /home/{{s_var_user}}/.bashrc
    KIND_HOME=/home/{{s_var_user}}/util/kind/{{s_var_kindcli}}
    PATH=\$KIND_HOME/bin:\$PATH
    EOF'

#- name: Apply .bash profile
#s  command: source /home/{{s_var_user}}/.bashrc
