---
- name: Get kubectl CLI binary
  get_url:
    url: https://dl.k8s.io/release/{{s_var_kubectl}}/bin/linux/amd64/kubectl
    dest: /home/{{s_var_user}}/kubectl-linux-amd64
    owner: "{{ s_var_user }}"
    group: "{{ s_var_user }}"
    mode: 0755

- name: Checking if the binary file exists
  stat: 
    path: /home/{{s_var_user}}/kubectl-linux-amd64
  register: kubectl_cli_origin_file_data

- name: Move content of decompressed archive to directory
  copy:
    remote_src: true
    src: /home/{{s_var_user}}/kubectl-linux-amd64
    dest: /home/{{s_var_user}}/util/kubectl/{{s_var_kubectl}}/bin/kubectl
    owner: "{{ s_var_user }}"
    group: "{{ s_var_user }}"
    mode: 0755
  when: kubectl_cli_origin_file_data.stat.exists

- name: Update binary permissions for pre-adjustment
  file:
    path: /home/{{s_var_user}}/util/kubectl/{{s_var_kubectl}}/bin/kubectl
    owner: "{{ s_var_user }}"
    group: "{{ s_var_user }}"
    mode: a-x

- name: Update binary permissions for alignment
  file:
    path: /home/{{s_var_user}}/util/kubectl/{{s_var_kubectl}}/bin/kubectl
    owner: "{{ s_var_user }}"
    group: "{{ s_var_user }}"
    mode: 0755

- name: Add binary to PATH and .bash profile
  command: |
    sh -c 'cat << EOF >> /home/{{s_var_user}}/.bashrc
    K8SCTL_HOME=/home/{{s_var_user}}/util/kubectl/{{s_var_kubectl}}
    PATH=\$K8SCTL_HOME/bin:\$PATH
    EOF'
